# If you are using derby, hsqldb, h2 or mssql with one of the ActiveRecord
# JDBC adapters, configure your database setting as the example below:
#
#development:
#  adapter: mssql
#  username: <username>
#  password: <password>
#  hostname: localhost
#  database: dummy

# If you are using oracle, db2, sybase, informix or prefer to use the plain
# JDBC adapter, configure your database setting as the example below (requires
# you to download and manually install the database vendor's JDBC driver .jar
# file). See your driver documentation for the apropriate driver class and
# connection string:
#
#development:
#  adapter: jdbc
#  username: <username>
#  password: <password>
#  driver: com.ibm.db2.jcc.DB2Driver
#  url: jdbc:db2://localhost:5021/dummy

# SQLite version 3.x
#   gem install sqlite3
# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: jdbc
  username:
  password:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:50882;databaseName=NorthWind;integratedSecurity=true;

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: jdbc
  username:
  password:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:50882;databaseName=NorthWind;integratedSecurity=true;

production:
  adapter: jdbc
  username:
  password:
  driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:50882;databaseName=NorthWind;integratedSecurity=true;